### ISSUE TITLE
TS Worker Patch

### ISSUE THREAD

**Issue by devotox** [breejs/ts-worker#2]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@breejs/ts-worker@1.0.0` for the project I'm working on.

* Adding `ts-config-paths` so that module paths could be used
* and adding an `index.d.ts` type so it can be valid in typescript

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@breejs/ts-worker/index.d.ts b/node_modules/@breejs/ts-worker/index.d.ts
new file mode 100644
index 0000000..8d18e19
--- /dev/null
+++ b/node_modules/@breejs/ts-worker/index.d.ts
@@ -0,0 +1 @@
+declare module '@breejs/ts-worker';
diff --git a/node_modules/@breejs/ts-worker/src/worker.js b/node_modules/@breejs/ts-worker/src/worker.js
index 52ea617..8414930 100644
--- a/node_modules/@breejs/ts-worker/src/worker.js
+++ b/node_modules/@breejs/ts-worker/src/worker.js
@@ -1,5 +1,6 @@
 const { workerData } = require('worker_threads');
 
 require('ts-node').register();
+require('tsconfig-paths').register();
 
 require(workerData.path);
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by shadowgate15** [comment]
We are always happy to review PRs if you want to make one! 

I would suggest making them two separate ones as adding an option and types are two different features.

**Comment by titanism** [comment]
@devotox please submit a PR, we are closing this issue in the interim
